# Generated by Django 4.1.5 on 2023-09-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Bengali)')),
                ('image', models.ImageField(upload_to='images/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_bn', models.CharField(max_length=200, verbose_name='Name (Bengali)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_bn', models.TextField(verbose_name='Description (Bengali)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Bengali)')),
                ('original_image', models.ImageField(upload_to='images/product-variant-original')),
                ('diagram_image', models.ImageField(upload_to='images/product-variant-diagrams')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
