# Generated by Django 4.1.5 on 2023-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_bn', models.CharField(max_length=200, verbose_name='Name (Bengali)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_bn', models.TextField(verbose_name='Description (Bengali)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
