# Generated by Django 4.1.5 on 2023-09-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_bn',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_bn',
            new_name='name_ar',
        ),
    ]
