# Generated by Django 4.2.5 on 2023-09-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('original_image', models.ImageField(upload_to='images/product-variant-original')),
                ('diagram_image', models.ImageField(upload_to='images/product-variant-diagrams')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
            preserve_default=False,
        ),
    ]
