# Generated by Django 4.2.5 on 2023-09-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_description_bn_product_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ar',
            field=models.TextField(verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=200, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description_ar',
            field=models.TextField(verbose_name='Description (Arabic)'),
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_properties', models.ManyToManyField(blank=True, to='product.customproperty')),
            ],
        ),
    ]
